services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile

    container_name: presight-server

    ports:
      - "3000:3000"

    volumes:
      - sqlite-data:/app/server/database
    
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/users"]
      interval: 30s
      timeout: 5s
      retries: 3

    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/Dockerfile

    depends_on:
        - server

    container_name: presight-client

    ports:
      - "5173:80"

    restart: unless-stopped
  
volumes:
  sqlite-data:
   name: presight-sqlite-data